apiVersion: ENC[AES256_GCM,data:7MMoptjj8WCaFcoo4vnjww7fyAM=,iv:PoEtgPSXGCwJEXIrNfdiJ7thJBqChPWzUIg4uaD3Ytc=,tag:FBlUPcBeqKfE6IZryv+Nsw==,type:str]
kind: ENC[AES256_GCM,data:hQBq4+stNA==,iv:k2TMOTAoyJddUcG12HW9yp4ZEYS8r5fUQT+mGD47P6U=,tag:m+ic7YtGXu0w8w5elgnuYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B+N15G7Vb0rJ1Ec=,iv:Oh/TpVPZpLNvhXxErZqlJ/nUum5+bOfJ5rM9Mef6r8c=,tag:B0piy4BL6FaT+dQPoU37Ug==,type:str]
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: ENC[AES256_GCM,data:NT2q,iv:WuBHzG9ulgo9XCmiF/G4eW6AJomwOMxcLDwUEjRPw24=,tag:/hJRDXqgOC/IkMAGl0c2OA==,type:str]
spec:
    rules:
        - host: ENC[AES256_GCM,data:1F1m8KENnPD1PJmDw+r/tDbGlwM=,iv:ynraeH4+y9sPgikqS+VLf7HADIkwxX2nu6SK3lpKEw8=,tag:Db3fuBDUN1piEwEhb96rsg==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:YylXuLw=,iv:RMX1hsaGh3KTzLGy55ZO25+hFmUCfeneGUn5BshuSsw=,tag:to0HlAh92YeXGtvH2ZFfaw==,type:str]
                  pathType: ENC[AES256_GCM,data:IPG836Gw,iv:JLdnmbAs4HdhiLz+OdkrUIyHh6MYV3L3SS7IXAqdmmk=,tag:f6MUbPOZtvmX1TWNfgJMNg==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:enKETPHvFEtLiWdjEe7msg==,iv:6mEUmxbroPcExvcJHnjT77WhdztGrGSyxPPS3w84aPY=,tag:uGxE4+6wx2Ri6hLTzoOhTA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:noGLjQ==,iv:UURZDBHzrNeaqsYv1Tk55Xl/uKjytaKFNOmmnM5GjMo=,tag:veBeYPNR+b56Vowjqkq+tQ==,type:int]
                - path: ENC[AES256_GCM,data:WLn2Lp1k,iv:ft/t73bL+IpiB/qMwunSqVy1rFyx4PKkMJTUjgE4nV8=,tag:10LSUo6SCDcd5shQ9vJjMw==,type:str]
                  pathType: ENC[AES256_GCM,data:TfUMagFb,iv:vb0uNiWlD4uLGWawI77b4tcoxsjbAdehCZ2y5Afw86M=,tag:DBcRltDIiI9PTQvlnB8SgA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:XEVLw6gDmihkN3cruJZVRQ==,iv:xuxN2bkFDEBsYl0134TtOAAYxWl+y0RxepiUgB2WKAE=,tag:MM+U/lkY2P9upiLYv0qTxw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:P1+jeA==,iv:3p+Edkb8qthfBU+6t0JE7KaXKcVB/IQ5OL8IaAsVZ0s=,tag:FMJxLvdaXLlDq5UZq8ntsw==,type:int]
                - path: ENC[AES256_GCM,data:xsRzYwYQ,iv:+4fjZbsYTbxZJ5n+Nl4s4INmrnNvt8xKr5jsVW2hSEI=,tag:BEJFzbwEQ3LPR614NMJtUQ==,type:str]
                  pathType: ENC[AES256_GCM,data:KL2wQP5n,iv:D+AeSfbp/Zjtk01Jc/DrGN5B4prr3ARq34D3J0QGerI=,tag:hwe8N9JgUqIKQDYEu6Fu+Q==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:yahdu2w+inw90QzLzWbn/A==,iv:rLqPB5vgFQs03P9E6WWkZpRvBb3bsjp1cLkGeA/Fe0A=,tag:B6Z5KTZ1BmHBFdl3xsCsFA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:aWdrNA==,iv:7Jz/KC+0jLzmm66WgqmBObbNwFhWTg7w4JOdz3MwqxQ=,tag:XekxAmceSHHDvnasohNYBw==,type:int]
                - path: ENC[AES256_GCM,data:CCP9AlSbSfKyX9oS,iv:S5I4eSuS9r3LhRAylyU/C6hqHLzGU0f6oMwljWPfNtE=,tag:H+COLqrnPheT8Ia6VOxpsw==,type:str]
                  pathType: ENC[AES256_GCM,data:VrwW2qg=,iv:w7Tu9N9PcybSnoP1KfIymU5iOpGz2hPjg4fTwsaGFVE=,tag:W41Z1H9SP/dWdT1rLgEqqg==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:f22DlNdCu6XlgpBR/Fpz1g==,iv:6OqBRzCHtSTpDWaVWFZ3PqZF+8rdxsMF5oTkKSkiVGw=,tag:vit2jVh8dv8/p9wuetxnpQ==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:GocWTA==,iv:CzO7aM5dSATan0LyAEN3JOTlsXoRWGLer8ePQJniwl4=,tag:iwvE5+PStphzcMhuSJHIWQ==,type:int]
                - path: ENC[AES256_GCM,data:6N/Bf0iBENjspABzndE=,iv:1GxkVk1vYirGqPtuy0KXBHAhcz9I6PD5u++7A9exSxo=,tag:z8JkxGsxAoh/senSKCooTQ==,type:str]
                  pathType: ENC[AES256_GCM,data:ltYlrB/Q,iv:SXCXWYWD92tOeAsUedaAQS6FcpIUWplqwES8lPlA5SU=,tag:q881ij5AEpRK5H9cVIIQyg==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:wwMG9rSkmno/DMVS7W+VqA==,iv:FEeG+4F44jQWPwfKQMvK5cVW11a18NtJDktJ+9RCSus=,tag:vPuQP+2U2bAKuWBFopfLMg==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:izoniQ==,iv:KuNtxCdD//RzbvOQaCUiWGUlzhC4Y3k1v3p0nbFMhdk=,tag:TbSRZP4dt0h9YRcWWm5uzQ==,type:int]
                - path: ENC[AES256_GCM,data:7sOZ7H/T9IHozoSHHTZX,iv:p1g8DQzZ/UoJh5raGJzD5z/ZF9vr3IXrHOTOMZz5JBs=,tag:h+oNdRhT6y/Zb8I09Y2IUQ==,type:str]
                  pathType: ENC[AES256_GCM,data:FFe63j9t,iv:ysgWU+idJKJRWYo3JbijUQ3sU3DfF2oeZp+E7+DeaRU=,tag:XCQ9VOQDVj0oXxE2PghB8Q==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:W8ZAjyUrz1U1qJ5D1HyVxQ==,iv:qb23sg5V7tUXrujf8rnt9tYY9i5PZ2s+rw6h2EQCCHM=,tag:PyupcbchrMzHV3w0DcjOVw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:Cv+qHQ==,iv:Fy8NY06Fg5svGed/S4azfKJ7sqON4+dYHJU+k5FU8LY=,tag:RsjPaC4CehJipCisR8CCyQ==,type:int]
                - path: ENC[AES256_GCM,data:Z0MKdzfyVwAn8A==,iv:+mH9lcwL7231jlOjtfLVxvHkSVthZlVpWZZ0TTB9E4o=,tag:PfqIKOiUz4UUy88bxDD+6w==,type:str]
                  pathType: ENC[AES256_GCM,data:6u5SPJgj,iv:pnClR7y3ivM6wefkkPNgJWPJ1pfhUU1z3mjmsh/OUFo=,tag:TDBUu4/QnKP67YWWwqlfpQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:yXWDprc4WGb8ql5gUP8n+g==,iv:kZ6EiId/Hd7AuRJrbEgvDx962Ukh9JHVD0MyjWJ/0J0=,tag:HRG9FNI/6rsC7elT1OPvhg==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:9wAyHA==,iv:NGjit9O/YEFCwLZPhEVgl8UuDW90V/fYEb6Ya3TSCWo=,tag:eI6peaKYp2Bk73MHVO+wfg==,type:int]
                - path: ENC[AES256_GCM,data:5UFtrbudhovm,iv:ahV0AEZn1fl4t5XsyFtK5BQte1pw16c3gmC1gfhZNSE=,tag:buwXHB2t0t54Y0ENk5lMoQ==,type:str]
                  pathType: ENC[AES256_GCM,data:tI6L0dvF,iv:LI4c2oV7fFc4fqK9OP2cbXZtPuJVK3kb/k44GZDdVOg=,tag:/lf7OPbYwOfRPoyQLY/a2g==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:skmYFFjQbXxuBSrffj785A==,iv:pMfDibQhil91dqgeJO9p4Xu2ErdqcB1wNJoC0zlhKnM=,tag:GMiBjwa7sKsk6Ulj8fNGaw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:Ckvg3g==,iv:4ZpmjBTXz2fJ3Yy83f0WFw7ieXnZBrxQYjbAr/m6yHQ=,tag:hA1USP5FhgRZ/YRMZ60rEg==,type:int]
                - path: ENC[AES256_GCM,data:emkjm5Z9yHdN7g==,iv:LmF5W38B5D6kagVn25BTV9JfNnqepnrScPAXAnbC6oc=,tag:/DRfnfJDF3il3BZwiOg68w==,type:str]
                  pathType: ENC[AES256_GCM,data:Mg0kroXK,iv:Ia+vKH3qzffQP75DazpQNMiTDKQjZf1CI6lp1l/9ELk=,tag:PsqPRlWp4VdskXwhXeuP1Q==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:wHl196LKNhfUYCMlidDHJA==,iv:dg6LXir98fa6pDoOSwyr0bgwSBTtg4zpV/uVEvXFZj4=,tag:HixUPMMbBPzXfqSEsK14cQ==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:YNAyBQ==,iv:VE1ynMoZ6bwapK1qRnP9SQFje4hyfZRbzUg5UCsv12Y=,tag:K2Q1itM0k8oCE7pcHMQNfw==,type:int]
                - path: ENC[AES256_GCM,data:YXRkBhI=,iv:yueETPiDvKzwlWaqaWHYWl9WhnyZP2Ls5elh0YpGhG0=,tag:IdiqTYpG1Vc/5dcbQuGyzA==,type:str]
                  pathType: ENC[AES256_GCM,data:db71MG+Q,iv:uIAlbBaycLFVoDWXLEUCl22jz9i5Em4LVEA3LpVu91w=,tag:5GbLadtODmhwjDkWSPNIMw==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:lXniLNNVEVNhPU6JNTgt8A==,iv:sl1QGUqXrYCS1+Uk2MXZDI07SdcYb9pdJM69xADiEb0=,tag:4ae8xpYjsV/jfj+phy8GDA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:wUOctg==,iv:2wQDN5jBn0/Hl07VnnwJ6AZW9jmgM6PonAGagjXdPuU=,tag:zd87Epe9uFlOu5e8eEiUBQ==,type:int]
                - path: ENC[AES256_GCM,data:M+8UbVLCgmO2OPaOb67vPpRJ4DOC,iv:5A+9AOdMxpCZl41u3C72Bsc6uWOv+/mozT5yOynsEc8=,tag:Ka1gtjswu+Kz1RIKIR4cOw==,type:str]
                  pathType: ENC[AES256_GCM,data:cVupsMnJ,iv:Wx3yLghjYM99qV5TLn9qIYaA65M9rJ0K4jwc9dEXK0k=,tag:Nj5AMCtdfK2ailxotlHP5w==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:ZVsYg2BO1dp6d3h2KYYs2A==,iv:Htzl0YD1IMyd97ore7LFIpmAEmfeNoVB8dcqmsrJrYM=,tag:grxm1Pk3Kdlv0XiFekKTpg==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:jr9d1w==,iv:rkxDASkwJzIM3DwKTjD6vybcMp2T3lj9adELxzFytoY=,tag:qFmZBiI4yHA64Un0iBV46Q==,type:int]
                - path: ENC[AES256_GCM,data:AIsyaM/N0h3W,iv:aTNt7VhaTWlfu1XpQp3P20oZnag+HaNkGtbJqBSSZUU=,tag:/XZxH56Px0iOkNU8wADoDw==,type:str]
                  pathType: ENC[AES256_GCM,data:BDI4eAO3,iv:jh3dwIMkIt+fMgOIFQqX3zx7SfvHDmmNXVTfK8bQpPE=,tag:OWsGU4L6/a8TthIhPuoLxw==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:7j+EOrUcZsb2rjPVWShuBg==,iv:XatKwzViTz2bAXeS2FYlp4nJkHr9fyXH2OZRlqXw7I4=,tag:01NV3qXxbm5Lr9GurSFqeQ==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:hG7Fsg==,iv:tePTonAY2DKk3lZFrILaJpA8bmGx2YAvlDrS27jg94w=,tag:5nG38Mc4z2MsIzByvCZDMQ==,type:int]
                - path: ENC[AES256_GCM,data:FbghNjTT6BHgobo=,iv:l7GpieaNoAw0d5PGHSd5axQkygVpBDrEb4qZcVI/vH4=,tag:mmeqDjOZineY9Oc89LgKkg==,type:str]
                  pathType: ENC[AES256_GCM,data:lOU5DOLY,iv:sF9IgdSIkvh/htcaMbwmoUGBuLscTMUsnmp1zIXlvGc=,tag:rpBMRdTvw4Pkvt7cRROFmg==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:xoVr1RYZNntfQKpB3fSYAQ==,iv:+HBmKzxCmgK3EanNP1KY0vlF1DzrtHI9r+LrjKucw/E=,tag:XEmVJ1zNZ6ahNRf54GtQXw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:xsbb5A==,iv:yDN3ew5u5s2PUg3Tp7IPRtsX7eiFOJ45nbaTerAxiXU=,tag:9Sx56etVI6HmFolBEKnzYw==,type:int]
                - path: ENC[AES256_GCM,data:i6qFdsXE,iv:wuPEoskN/fdSKqq0E5i630RAdpoCPPwwneYdYWjw1HM=,tag:Ldc/XyOtn/P0MqsH8iWKDA==,type:str]
                  pathType: ENC[AES256_GCM,data:kfuemc1F,iv:pj1XNv+gvG7jj5ygRiHlhMlVOK7lI38iYZAWdxSgQDQ=,tag:+NDbH9lLHbkwt3cgVAex0A==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:auFK1SYUrUdYpzmHpX+rZA==,iv:tvUdReZYfMrzmwLRv4cEavGhtInP6sshuGSM1CG7IuE=,tag:Ng5JEBJcQVhq6uhTHNmEfA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:2kqSrw==,iv:m2oD0FjDOukKHvF3mJuz7AoFkVN+q+HN3fgBDS1UPZE=,tag:mfkTY9MGCTXQd4SB+5u5Tw==,type:int]
                - path: ENC[AES256_GCM,data:t25s7lCz4aUAiw==,iv:7yF8K8VgsZ3VHGYEn34vdQ+WfvYbIetxrXME5hD5ABc=,tag:Emucl2D4TgsnxRrd8A1/fg==,type:str]
                  pathType: ENC[AES256_GCM,data:XQMzy3GQ,iv:k38LsS7NRmlA04hgIVw/SawxCLpLLMQxgI/IV2qLHO8=,tag:NKiXg3mzJQw0aikkO32UPQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:AMbQ+wyO1mXQ4GQL7lh3ZQ==,iv:TJNRZuihepA1OLNc46HFPnF+gmXnyOyF0azdBf0YVcw=,tag:/o21tfI2SKfwjY6bQZ+6Gw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:yr9ufg==,iv:FJahK281qyALlVZx9hs/RqMOczST1vNKdXkFQgfazx0=,tag:znwCKcdbd9r+SpHpJxbd6g==,type:int]
                - path: ENC[AES256_GCM,data:rC6s9151R8zEzA==,iv:cEfk4eiW79oVi5pBBctf+jZLEhByJCqzm/6NvEhXKmA=,tag:qdkrNCr7iD3mMsyBYtORlw==,type:str]
                  pathType: ENC[AES256_GCM,data:DO1rrYrc,iv:VG0MEBXKnkeTwLLk+iGJM2qPFOk5xFu1CTyvbUw9Z1Y=,tag:N8n88LYTTNoMrkZZkzSH2Q==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:HpAajWKUeSeJBCXQ5lJkng==,iv:CXp9nuCQ7XspxCMz8j470HRHtNdTYokTeVB96jjYig4=,tag:nnVEbngI/xsZAuwGedWoOg==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:FOYZ/g==,iv:2C3x5oyzRsyxLuf0tPb+BDgEJTH4dnY3KwCmmbaLKfc=,tag:6QkpcXEqKHht4JYvSyJHeQ==,type:int]
                - path: ENC[AES256_GCM,data:n3uh9rVz,iv:XhiAEUVEOAy4Tk1NFivj0MKIKEvScYxu/2/fVMhOjPU=,tag:ilRFdG/F7MzhoR+Uu7GNEQ==,type:str]
                  pathType: ENC[AES256_GCM,data:ocbQL53M,iv:WwCJif4GnoUYq6nHLqOMeUFRfNeGlxZE/nHoaHUglxs=,tag:oSspfGDpjzXp9/PhLJLuhg==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:Joqm9/5tUlQXWIxIve0Vzw==,iv:fOG6sGl4Ouq45mHMApN4UauJ6eBpizNQMCgOF65a8mk=,tag:lgxryueXmnarszTmejIBmg==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:EHC0EA==,iv:jSl2v0lZn/z50SCU8NVYzo9kn2Or2r3vUCtWMtBOj+A=,tag:A24yt5CyX7JlHgi5IR2NTw==,type:int]
                - path: ENC[AES256_GCM,data:HofvpmGNhg==,iv:JRHNZM+rKwvAbf0oiFQm1DXBltzzT+p3UOI/Zg4Ch6s=,tag:Lp6zN0onDCN4997JkXoahQ==,type:str]
                  pathType: ENC[AES256_GCM,data:yDarm10=,iv:fUR8YQ2yoexC4AfAjeWs3v594m1+/4ZmeQKbqGsOC3A=,tag:xxq+nOOYMOwQl7EhQSr5oQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:Gz3ZbA5zzwaFu0K+dDmZ2w==,iv:6rGxP6TJ72xCtE8z4Vbp6VuYKEXh79nAt5rqF28YzL4=,tag:1HcJqxa41TVqh45kKHbDpw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:9IbAyg==,iv:G4QrhYkzUkCrdFVGDlrfD2ocjLRYcy+XmHQmxk4QETA=,tag:xDoIYFTdgsVrb/tayqlxhA==,type:int]
        - host: ENC[AES256_GCM,data:MI1qMKnqy8lZc2nudalixmdIPgo=,iv:cffLincrIMTF8Asbm42MD3TILs15hlImcsAc2auNaCc=,tag:gHanAds7SC7gn0jtAqoypw==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:Rg==,iv:TDXhAPyTjRE6XsbNL0VRuClME1UFqDzeODdJcrsSI/M=,tag:X7LmOF5pQCgIfpbIhrhaXA==,type:str]
                  pathType: ENC[AES256_GCM,data:H5twgiX8,iv:DeJ8tRB8X18WasVUJp62x7hZJA9PmmbO9LglZzHeYTw=,tag:z1HzqV+ac0OptAvplt318g==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:Isnpl5/Q6aBg9VSM,iv:02MATdwXKFyR/9Wl4gl95JNyYmilMti0/1HNY1yHuDU=,tag:3u6eyMmpHpoHFk+YMZgpzA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:dLI=,iv:43KIcrOFG0/MymcfZTuWgBl5TRKP/8ab/2PkA8Ln+Mg=,tag:ZN/P8VIC3wNVg/Otr/y2AA==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWU1XSmFUcHFpc2kwU2dR
            UU9EU0FlZGZYekw0RFVSS05ERVZDSTNoRG13CnUyRHRSMkZGekovUmVMcjJZdzEv
            NmJ4b2t4QzdabHZ6TUMwN0IvSHZ6T28KLS0tIDBseWVmUi9sWU5iOEU3UU1tOFJx
            WE5CeFNMUkxBUWVCMXlIanhZY0VkQ1EK9rI2BGJ+xVG3dk1E1MpgiECxH6D7Zp6z
            6BN1DCf3mh4ms2lZJ1edOe9fRSgoP5mTHIxvZ6/0+adKynoiaWQrsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13jthku4399se3fvnapyzhzs2f3aall30jkx4klz3k7nalkr0wdmsh5a8h5
    lastmodified: "2026-08-29T22:23:57Z"
    mac: ENC[AES256_GCM,data:sxudROsCrq/XeIHad/5qdUy412jGyzbSAW4qFVDFGLFzIonwdguQH7gu0W700sqPYp5QxUtleysShB8i1SwFipNVFHdxsEoZIvFyv2S/iGmF9B1fYGsut1TiuIoB2yD6eS9kxqk8JT/dvDeLUBWxZUhsx6iPaoCUUS5VItrM6EU=,iv:66goOVgDdCnGeFNMS9jqNbG/Dh/ClyHJhUxmm/nyYrs=,tag:M/NCeWR33aBWxWi0hUKSQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
